### PR TITLE
Show associated branch prs

### PR DESCRIPTION
**Pull request by yakov116**
Test On 

https://github.com/pnarielwala/create-react-app-ts/branches
https://github.com/jack1142/Red-DiscordBot/branches

https://github.com/talknsmile/TestR/branches //This has all 6 types

image

<!--

Thanks for contributing! 🍄

1. LINKED ISSUES:
   Does this PR close/fix an existing issue? Write something like `Closes #10`

2. TEST URLS:
   Add some test URLs

3. SCREENSHOT:
   Add a screenshot here if your PR makes visual changes

### CODE REVIEW

**Comment by yakov116** [comment]
@jack1142 in the mood of testing.

I cant send a PR. if you want you can. However the picture needs to be updated

**Comment by jack1142** [comment]
@yakov116 I was planning on finishing your PR and sending it, I just haven't had time to do that yet. Thanks for the mention though :)

**Comment by yakov116** [comment]
I fixed the 2 issues. Only the picture needs updating

**Comment by yakov116** [comment]
@jack1142 I tested it and I think I got every case in. When you have time, if you could send it. I really worked hard on it, was very sad that it was trashed.

**Pull request closed without merging**
